config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => {:registrations => "registrations"}
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  get "/home/index", to: "home#index"
  root "home#index"
  resources :posts do 
    resources :comments 
  end

  resources :comments do
    resources :replies, only: %i[ new create edit update delete ]
  end
  
  resources :category, only: %i[ index new create edit update ]
end

app/models/reply.rb
class Reply < ApplicationRecord
  belongs_to :comment
  belongs_to :user
  
  validates_presence_of :body
end

app/controllers/replies_controller.rb
class RepliesController < ApplicationController
  
  before_action :set_reply, only: %i[ new destroy edit update ]

  def show

  end

  def new
        @reply = @comment.replies.build
  end

  def create
      @comment = Comment.find(params[:comment_id])
      @reply = Reply.new(reply_params)
      @reply.comment_id = @comment.id
      @reply.user_id = current_user.id
      if @reply.save
        redirect_to post_comment_path(@comment.post.id,@comment.id)
      else
        redner :new, status: :unprocessable_entity
      end
  end

  def edit
    @reply = Reply.find(params[:id])
  end

  def update
    @reply = Reply.find(params[:id])
    if @reply.update(reply_params)
      redirect_to post_comment_path(@comment.post.id,@comment.id)
    else
      render :edit
    end
  end

  def destroy
    @comment = Comment.find(params[:comment_id])
    @reply = Reply.find(params[:id])
    @reply.destroy
    redirect_to post_comment_path(@comment.post.id,@comment.id)
  end

  private

    def set_reply
      @comment = Comment.find(params[:comment_id])
    end

    def reply_params
      params.require(:reply).permit(:body)
    end
end

app/helpers/replies_helper.rb
module RepliesHelper
end

app/views/replies/edit.html.erb
<h1 class="text-center text-success">Edit Reply</h1>

<% content_for :head do%>
    Reply Edit
<% end %>
<p class="text-center text-primary ">Add Reply</p>
<%= form_with model: @reply,url: comment_reply_path(@comment.id,@reply.id)  do |form| %>
    <div class="row justify-content-center">
        <div class="col-lg-3">
            <div class="form-group">
                <%= form.label :body, style: "display: block" %>
                <%= form.text_field :body, class:"form-control" %>
            </div>
        </div>
    </div>

    <div class="row justify-content-center mt-3">
        <div class="col-lg-3">
            <%= form.submit "Add Reply", class:"btn btn-success" %>
        </div>
    </div>


<% end %>

app/views/replies/new.html.erb
<h1 class="text-center ">
    Reply the comment
    <span class="text-success"><%= Comment.find(params[:comment_id]).body
 %></span>

<% content_for :head do%>
   Add Reply
<% end %>

</h1>
<p class="text-center text-primary ">Add Reply</p>
<%= form_with model: @reply,url: comment_replies_path  do |form| %>
    <div class="row justify-content-center">
        <div class="col-lg-3">
            <div class="form-group">
                <%= form.label :body, style: "display: block" %>
                <%= form.text_field :body, class:"form-control" %>
            </div>
        </div>
    </div>

    <div class="row justify-content-center mt-3">
        <div class="col-lg-3">
            <%= form.submit "Add Reply", class:"btn btn-success" %>
        </div>
    </div>


<% end %>