config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => {:registrations => "registrations"}
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  get "/home/index", to: "home#index"
  root "home#index"
  resources :posts do 
    resources :comments 
  end

  resources :comments do
    resources :replies, only: %i[ new create edit update delete ]
  end
  
  resources :category, only: %i[ index new create edit update ]
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user
  has_many :replies, dependent: :destroy

  validates_presence_of :body, length: { minimum: 3 }
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  before_action :set_comment, only: %i[ new show edit update destroy ]

  def new
    @comment = @post.comments.build
  end

  def show
  end

  def edit
    @comment = Comment.find(params[:id])
  end

  def update
    @comment = Comment.find(params[:id])
    if @comment.update(comment_params)
      redirect_to post_comment_path(@post.id,@comment.id) 
    else
      render :edit, status: :unprocessable_entity
    end
    
  end

  def create
      @comment = Comment.new(comment_params)
      @comment.post_id = params[:post_id]
      @comment.user_id = current_user.id
      @comment.commentor_email = current_user.email
      if @comment.save
          redirect_to root_path
      else
        render :new, status: :unprocessable_entity
      end
  end

  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy
    redirect_to post_comment_path(@post.id,@comment.id)
  end

  private
   def comment_params
    params.require(:comment).permit(:body)
   end

   def set_comment
    @post = Post.find_by(id: params[:post_id]) 
   end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/edit.html.erb
<h1 class="text-center text-success">Edit Your Comment</h1>
<%= form_with model: @comment, url: post_comment_path(@post.id,@comment.id) do |form| %>
    <div class="row justify-content-center">
        <div class="col-lg-3">
            <div class="form-group">
                <%= form.label :body, style: "display: block" %>
                <%= form.text_field :body, class:"form-control" %>
            </div>
        </div>
    </div>

    <div class="row justify-content-center mt-3">
        <div class="col-lg-3">
            <%= form.submit "Edit Comment", class:"btn btn-success" %>
        </div>
    </div>

<% end %>

app/views/comments/new.html.erb
<h1 class="text-center text-success ">Add Comment</h1>

<div class="row justify-content-center m-3">
    <div class="col-lg-3">
        <%= image_tag(@post.picture, size:"100x100") %>
    </div>
</div>

<%= form_with model: @comment, url: post_comments_path do |form| %>
    <div class="row justify-content-center">
        <div class="col-lg-3">
            <div class="form-group">
                <%= form.label :body, style: "display: block" %>
                <%= form.text_field :body, class:"form-control" %>
            </div>
        </div>
    </div>

    <div class="row justify-content-center mt-3">
        <div class="col-lg-3">
            <%= form.submit "Add Comment", class:"btn btn-success" %>
        </div>
    </div>


<% end %>

app/views/comments/show.html.erb
<div class="main_div">
    <p class="text-center">Commets By
        <span class="text-green"><%= @post.user.email %></span>
    </p>
    <div class="row justify-content-center">
        <div class="col-lg-4">
            <%= image_tag(@post.picture,size: "150x150") %>
        </div>
    </div>

    <div class="row justify-content-center">
        <div class="col-lg-4">
            <% @post.comments.order(id: :desc).each do |comment| %>
                <p>
                    <b>Comment Body</b>
                    <%= comment.body %>
                </p>
                <% comment.replies.order(id: :desc).each do |reply|%>
                <p>
                    <b>Reply Body</b>
                    <%= reply.body %>
                </p>

                <p>
                    <% if can? :edit, comment %>
                        <%= link_to "Edit Reply", edit_comment_reply_path(comment.id,reply.id) %>
                    <% end %>
                    <% if can? :destroy, comment %>
                        <%= button_to "Delete Reply", comment_reply_path(comment.id,reply.id), method: :delete, class: "btn_reply" %>
                    <% end %>
                </p>

                <p>
                    <%= time_ago_in_words(reply.updated_at) + " ago" %>
                </p>

            <% end %>

            <div class="row">
                <div class="m-2">
                    <b>Commentor Email
                    </b>-
                    <%= comment.commentor_email %>
                </div>
                <div class="mt-2">
                    <% if can? :destroy, comment %>
                        <%= link_to "Edit", edit_post_comment_path(@post,comment.id) %>
                    <% end %>

                    <% if can? :new, comment %>
                        <%= link_to "Reply", new_comment_reply_path(comment.id), style: "margin-left: 90px;" %>
                    <% end %>
                    <% if can? :destroy, comment %>
                        <%= button_to "Delete", post_comment_path(@post,comment.id), method: :delete, class: "btn_class" %>
                    <% end %>
                </div>
                <div class="m-2">
                    <p>
                        <i>
                            <%= time_ago_in_words(comment.updated_at) + " ago" %>
                        </i>
                    </p>
                </div>
                <div class=""></div>
            </div>
        <% end %>
    </div>
</div></div>