config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => {:registrations => "registrations"}
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  get "/home/index", to: "home#index"
  root "home#index"
  resources :posts do 
    resources :comments 
  end

  resources :comments do
    resources :replies, only: %i[ new create edit update delete ]
  end
  
  resources :category, only: %i[ index new create edit update ]
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<% content_for :head do %>
    Home
<% end %>

<% if Post.count > 0 %>
    <div class="row m-2">
        <% Post.all.each do |post|  %>
            <div class="col-lg-3 mt-2">
                <div class="card" style="width: 18rem;">
                    <%= image_tag(post.picture,size:"150x150",class:"card-img-top rounded") %>
                    <div class="card-body">
                        <h5 class="card-title"><%= post.title %></h5>
                        <p class="card-text"><%= post.body %></p>
                        <div class="row">
                            <div class="col-lg-3">
                                <%= link_to "Comment", new_post_comment_path(post), class:"btn btn-primary " %>
                            </div>
                            <div class="col-lg-3" style="margin-left: 50px;">
                               <%= link_to "ShowC", post_comment_url(post.id,post.comments), class:"btn btn-primary " %>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        <% end %>
    </div>
<% end %>